name: ${NAME}

services:
    info_go:
        build:
            context: .
        restart: unless-stopped
        container_name: info_go
        environment:
            - PORT=8091
            - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
            - ENVIRONMENT=${ENVIRONMENT}
        ports:
            - "127.0.0.1:8091:8091"
        networks:
            - supabase_net

networks:
    supabase_net:
        external: true
